theme: jekyll-theme-midnight

title: 2X SDK
description: >- # this means to ignore newlines until "baseurl:"
  This is the official website for the SDK of the Shining3D 2X series scanners.
baseurl: "sdk.sn3d.tech" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com